// src/utils/locationData.js
// Enhanced location data for Vietnam with additional ward data

const locationData = {
  regions: [
    "An Giang",
    "Bà Rịa - Vũng Tàu",
    "Bắc Giang",
    "Bắc Kạn",
    "Bạc Liêu",
    "Bắc Ninh",
    "Bến Tre",
    "Bình Định",
    "Bình Dương",
    "Bình Phước",
    "Bình Thuận",
    "Cà Mau",
    "Cần Thơ",
    "Cao Bằng",
    "Đà Nẵng",
    "Đắk Lắk",
    "Đắk Nông",
    "Điện Biên",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Giang",
    "Hà Nam",
    "Hà Nội",
    "Hà Tĩnh",
    "Hải Dương",
    "Hải Phòng",
    "Hậu Giang",
    "Hòa Bình",
    "Hưng Yên",
    "Khánh Hòa",
    "Kiên Giang",
    "Kon Tum",
    "Lai Châu",
    "Lâm Đồng",
    "Lạng Sơn",
    "Lào Cai",
    "Long An",
    "Nam Định",
    "Nghệ An",
    "Ninh Bình",
    "Ninh Thuận",
    "Phú Thọ",
    "Phú Yên",
    "Quảng Bình",
    "Quảng Nam",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sóc Trăng",
    "Sơn La",
    "Tây Ninh",
    "Thái Bình",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thừa Thiên Huế",
    "Tiền Giang",
    "TP Hồ Chí Minh",
    "Trà Vinh",
    "Tuyên Quang",
    "Vĩnh Long",
    "Vĩnh Phúc",
    "Yên Bái"
  ],
  districts: {
    "An Giang": [
      "TP. Long Xuyên",
      "TP. Châu Đốc",
      "Thị xã Tân Châu",
      "Huyện An Phú",
      "Huyện Châu Phú",
      "Huyện Châu Thành",
      "Huyện Chợ Mới",
      "Huyện Phú Tân",
      "Huyện Thoại Sơn",
      "Huyện Tịnh Biên",
      "Huyện Tri Tôn"
    ],
    "Bà Rịa - Vũng Tàu": [
      "TP. Vũng Tàu",
      "TP. Bà Rịa",
      "Thị xã Phú Mỹ",
      "Huyện Châu Đức",
      "Huyện Côn Đảo",
      "Huyện Đất Đỏ",
      "Huyện Long Điền",
      "Huyện Xuyên Mộc"
    ],
    "Bắc Giang": [
      "TP. Bắc Giang",
      "Huyện Hiệp Hòa",
      "Huyện Lạng Giang",
      "Huyện Lục Nam",
      "Huyện Lục Ngạn",
      "Huyện Sơn Động",
      "Huyện Tân Yên",
      "Huyện Việt Yên",
      "Huyện Yên Dũng",
      "Huyện Yên Thế"
    ],
    "Bắc Kạn": [
      "TP. Bắc Kạn",
      "Huyện Ba Bể",
      "Huyện Bạch Thông",
      "Huyện Chợ Đồn",
      "Huyện Chợ Mới",
      "Huyện Na Rì",
      "Huyện Ngân Sơn",
      "Huyện Pác Nặm"
    ],
    "Bạc Liêu": [
      "TP. Bạc Liêu",
      "Thị xã Giá Rai",
      "Huyện Đông Hải",
      "Huyện Hòa Bình",
      "Huyện Hồng Dân",
      "Huyện Phước Long",
      "Huyện Vĩnh Lợi"
    ],
    "Bắc Ninh": [
      "TP. Bắc Ninh",
      "Thị xã Từ Sơn",
      "Huyện Gia Bình",
      "Huyện Lương Tài",
      "Huyện Quế Võ",
      "Huyện Thuận Thành",
      "Huyện Tiên Du",
      "Huyện Yên Phong"
    ],
    "Bến Tre": [
      "TP. Bến Tre",
      "Huyện Ba Tri",
      "Huyện Bình Đại",
      "Huyện Châu Thành",
      "Huyện Chợ Lách",
      "Huyện Giồng Trôm",
      "Huyện Mỏ Cày Bắc",
      "Huyện Mỏ Cày Nam",
      "Huyện Thạnh Phú"
    ],
    "Bình Định": [
      "TP. Quy Nhơn",
      "Thị xã An Nhơn",
      "Thị xã Hoài Nhơn",
      "Huyện An Lão",
      "Huyện Hoài Ân",
      "Huyện Phù Cát",
      "Huyện Phù Mỹ",
      "Huyện Tây Sơn",
      "Huyện Tuy Phước",
      "Huyện Vân Canh",
      "Huyện Vĩnh Thạnh"
    ],
    "Bình Dương": [
      "TP. Thủ Dầu Một",
      "TP. Dĩ An",
      "TP. Thuận An",
      "TP. Tân Uyên",
      "Thị xã Bến Cát",
      "Huyện Bàu Bàng",
      "Huyện Bắc Tân Uyên",
      "Huyện Dầu Tiếng",
      "Huyện Phú Giáo"
    ],
    "Bình Phước": [
      "TP. Đồng Xoài",
      "Thị xã Bình Long",
      "Thị xã Phước Long",
      "Huyện Bù Đăng",
      "Huyện Bù Đốp",
      "Huyện Bù Gia Mập",
      "Huyện Chơn Thành",
      "Huyện Đồng Phú",
      "Huyện Hớn Quản",
      "Huyện Lộc Ninh",
      "Huyện Phú Riềng"
    ],
    "Bình Thuận": [
      "TP. Phan Thiết",
      "Thị xã La Gi",
      "Huyện Bắc Bình",
      "Huyện Đức Linh",
      "Huyện Hàm Tân",
      "Huyện Hàm Thuận Bắc",
      "Huyện Hàm Thuận Nam",
      "Huyện Phú Quý",
      "Huyện Tánh Linh",
      "Huyện Tuy Phong"
    ],
    "Cà Mau": [
      "TP. Cà Mau",
      "Huyện Cái Nước",
      "Huyện Đầm Dơi",
      "Huyện Năm Căn",
      "Huyện Ngọc Hiển",
      "Huyện Phú Tân",
      "Huyện Thới Bình",
      "Huyện Trần Văn Thời",
      "Huyện U Minh"
    ],
    "Cần Thơ": [
      "Quận Bình Thủy",
      "Quận Cái Răng",
      "Quận Ninh Kiều",
      "Quận Ô Môn",
      "Quận Thốt Nốt",
      "Huyện Cờ Đỏ",
      "Huyện Phong Điền",
      "Huyện Thới Lai",
      "Huyện Vĩnh Thạnh"
    ],
    "Cao Bằng": [
      "TP. Cao Bằng",
      "Huyện Bảo Lạc",
      "Huyện Bảo Lâm",
      "Huyện Hạ Lang",
      "Huyện Hà Quảng",
      "Huyện Hòa An",
      "Huyện Nguyên Bình",
      "Huyện Phục Hòa",
      "Huyện Quảng Uyên",
      "Huyện Thạch An",
      "Huyện Thông Nông",
      "Huyện Trà Lĩnh",
      "Huyện Trùng Khánh"
    ],
    "Đà Nẵng": [
      "Quận Cẩm Lệ",
      "Quận Hải Châu",
      "Quận Liên Chiểu",
      "Quận Ngũ Hành Sơn",
      "Quận Sơn Trà",
      "Quận Thanh Khê",
      "Huyện Hòa Vang",
      "Huyện Hoàng Sa"
    ],
    "Đắk Lắk": [
      "TP. Buôn Ma Thuột",
      "Thị xã Buôn Hồ",
      "Huyện Buôn Đôn",
      "Huyện Cư Kuin",
      "Huyện Cư M'gar",
      "Huyện Ea H'leo",
      "Huyện Ea Kar",
      "Huyện Ea Súp",
      "Huyện Krông Ana",
      "Huyện Krông Bông",
      "Huyện Krông Búk",
      "Huyện Krông Năng",
      "Huyện Krông Pắk",
      "Huyện Lắk",
      "Huyện M'Đrắk"
    ],
    "Đắk Nông": [
      "TP. Gia Nghĩa",
      "Huyện Cư Jút",
      "Huyện Đắk Glong",
      "Huyện Đắk Mil",
      "Huyện Đắk R'lấp",
      "Huyện Đắk Song",
      "Huyện Krông Nô",
      "Huyện Tuy Đức"
    ],
    "Điện Biên": [
      "TP. Điện Biên Phủ",
      "Thị xã Mường Lay",
      "Huyện Điện Biên",
      "Huyện Điện Biên Đông",
      "Huyện Mường Ảng",
      "Huyện Mường Chà",
      "Huyện Mường Nhé",
      "Huyện Nậm Pồ",
      "Huyện Tủa Chùa",
      "Huyện Tuần Giáo"
    ],
    "Đồng Nai": [
      "TP. Biên Hòa",
      "TP. Long Khánh",
      "Huyện Cẩm Mỹ",
      "Huyện Định Quán",
      "Huyện Long Thành",
      "Huyện Nhơn Trạch",
      "Huyện Tân Phú",
      "Huyện Thống Nhất",
      "Huyện Trảng Bom",
      "Huyện Vĩnh Cửu",
      "Huyện Xuân Lộc"
    ],
    "Đồng Tháp": [
      "TP. Cao Lãnh",
      "TP. Sa Đéc",
      "TP. Hồng Ngự",
      "Huyện Cao Lãnh",
      "Huyện Châu Thành",
      "Huyện Hồng Ngự",
      "Huyện Lai Vung",
      "Huyện Lấp Vò",
      "Huyện Tam Nông",
      "Huyện Tân Hồng",
      "Huyện Thanh Bình",
      "Huyện Tháp Mười"
    ],
    "Gia Lai": [
      "TP. Pleiku",
      "Thị xã An Khê",
      "Thị xã Ayun Pa",
      "Huyện Chư Păh",
      "Huyện Chư Prông",
      "Huyện Chư Pưh",
      "Huyện Chư Sê",
      "Huyện Đắk Đoa",
      "Huyện Đak Pơ",
      "Huyện Đức Cơ",
      "Huyện Ia Grai",
      "Huyện Ia Pa",
      "Huyện KBang",
      "Huyện Kông Chro",
      "Huyện Krông Pa",
      "Huyện Mang Yang",
      "Huyện Phú Thiện"
    ],
    "Hà Giang": [
      "TP. Hà Giang",
      "Huyện Bắc Mê",
      "Huyện Bắc Quang",
      "Huyện Đồng Văn",
      "Huyện Hoàng Su Phì",
      "Huyện Mèo Vạc",
      "Huyện Quản Bạ",
      "Huyện Quang Bình",
      "Huyện Vị Xuyên",
      "Huyện Xín Mần",
      "Huyện Yên Minh"
    ],
    "Hà Nam": [
      "TP. Phủ Lý",
      "Thị xã Duy Tiên",
      "Huyện Bình Lục",
      "Huyện Kim Bảng",
      "Huyện Lý Nhân",
      "Huyện Thanh Liêm"
    ],
    "Hà Nội": [
      "Quận Ba Đình",
      "Quận Bắc Từ Liêm",
      "Quận Cầu Giấy",
      "Quận Đống Đa",
      "Quận Hà Đông",
      "Quận Hai Bà Trưng",
      "Quận Hoàn Kiếm",
      "Quận Hoàng Mai",
      "Quận Long Biên",
      "Quận Nam Từ Liêm",
      "Quận Tây Hồ",
      "Quận Thanh Xuân",
      "Thị xã Sơn Tây",
      "Huyện Ba Vì",
      "Huyện Chương Mỹ",
      "Huyện Đan Phượng",
      "Huyện Đông Anh",
      "Huyện Gia Lâm",
      "Huyện Hoài Đức",
      "Huyện Mê Linh",
      "Huyện Mỹ Đức",
      "Huyện Phú Xuyên",
      "Huyện Phúc Thọ",
      "Huyện Quốc Oai",
      "Huyện Sóc Sơn",
      "Huyện Thạch Thất",
      "Huyện Thanh Oai",
      "Huyện Thanh Trì",
      "Huyện Thường Tín",
      "Huyện Ứng Hòa"
    ],
    "Hà Tĩnh": [
      "TP. Hà Tĩnh",
      "Thị xã Hồng Lĩnh",
      "Thị xã Kỳ Anh",
      "Huyện Cẩm Xuyên",
      "Huyện Can Lộc",
      "Huyện Đức Thọ",
      "Huyện Hương Khê",
      "Huyện Hương Sơn",
      "Huyện Lộc Hà",
      "Huyện Nghi Xuân",
      "Huyện Thạch Hà",
      "Huyện Vũ Quang"
    ],
    "Hải Dương": [
      "TP. Hải Dương",
      "TP. Chí Linh",
      "Thị xã Kinh Môn",
      "Huyện Bình Giang",
      "Huyện Cẩm Giàng",
      "Huyện Gia Lộc",
      "Huyện Kim Thành",
      "Huyện Nam Sách",
      "Huyện Ninh Giang",
      "Huyện Thanh Hà",
      "Huyện Thanh Miện",
      "Huyện Tứ Kỳ"
    ],
    "Hải Phòng": [
      "Quận Đồ Sơn",
      "Quận Dương Kinh",
      "Quận Hải An",
      "Quận Hồng Bàng",
      "Quận Kiến An",
      "Quận Lê Chân",
      "Quận Ngô Quyền",
      "Huyện An Dương",
      "Huyện An Lão",
      "Huyện Bạch Long Vĩ",
      "Huyện Cát Hải",
      "Huyện Kiến Thụy",
      "Huyện Thủy Nguyên",
      "Huyện Tiên Lãng",
      "Huyện Vĩnh Bảo"
    ],
    "Hậu Giang": [
      "TP. Vị Thanh",
      "TP. Ngã Bảy",
      "Huyện Châu Thành",
      "Huyện Châu Thành A",
      "Huyện Long Mỹ",
      "Huyện Phụng Hiệp",
      "Huyện Vị Thủy"
    ],
    "Hòa Bình": [
      "TP. Hòa Bình",
      "Huyện Cao Phong",
      "Huyện Đà Bắc",
      "Huyện Kim Bôi",
      "Huyện Lạc Sơn",
      "Huyện Lạc Thủy",
      "Huyện Lương Sơn",
      "Huyện Mai Châu",
      "Huyện Tân Lạc",
      "Huyện Yên Thủy"
    ],
    "Hưng Yên": [
      "TP. Hưng Yên",
      "Thị xã Mỹ Hào",
      "Huyện Ân Thi",
      "Huyện Khoái Châu",
      "Huyện Kim Động",
      "Huyện Phù Cừ",
      "Huyện Tiên Lữ",
      "Huyện Văn Giang",
      "Huyện Văn Lâm",
      "Huyện Yên Mỹ"
    ],
    "Khánh Hòa": [
      "TP. Nha Trang",
      "TP. Cam Ranh",
      "Thị xã Ninh Hòa",
      "Huyện Cam Lâm",
      "Huyện Diên Khánh",
      "Huyện Khánh Sơn",
      "Huyện Khánh Vĩnh",
      "Huyện Trường Sa",
      "Huyện Vạn Ninh"
    ],
    "Kiên Giang": [
      "TP. Rạch Giá",
      "TP. Hà Tiên",
      "TP. Phú Quốc",
      "Huyện An Biên",
      "Huyện An Minh",
      "Huyện Châu Thành",
      "Huyện Giang Thành",
      "Huyện Giồng Riềng",
      "Huyện Gò Quao",
      "Huyện Hòn Đất",
      "Huyện Kiên Hải",
      "Huyện Kiên Lương",
      "Huyện Tân Hiệp",
      "Huyện U Minh Thượng",
      "Huyện Vĩnh Thuận"
    ],
    "Kon Tum": [
      "TP. Kon Tum",
      "Huyện Đắk Glei",
      "Huyện Đắk Hà",
      "Huyện Đắk Tô",
      "Huyện Ia H'Drai",
      "Huyện Kon Plông",
      "Huyện Kon Rẫy",
      "Huyện Ngọc Hồi",
      "Huyện Sa Thầy",
      "Huyện Tu Mơ Rông"
    ],
    "Lai Châu": [
      "TP. Lai Châu",
      "Huyện Mường Tè",
      "Huyện Nậm Nhùn",
      "Huyện Phong Thổ",
      "Huyện Sìn Hồ",
      "Huyện Tam Đường",
      "Huyện Tân Uyên",
      "Huyện Than Uyên"
    ],
    "Lâm Đồng": [
      "TP. Đà Lạt",
      "TP. Bảo Lộc",
      "Huyện Bảo Lâm",
      "Huyện Cát Tiên",
      "Huyện Đạ Huoai",
      "Huyện Đạ Tẻh",
      "Huyện Đam Rông",
      "Huyện Di Linh",
      "Huyện Đơn Dương",
      "Huyện Đức Trọng",
      "Huyện Lạc Dương",
      "Huyện Lâm Hà"
    ],
    "Lạng Sơn": [
      "TP. Lạng Sơn",
      "Huyện Bắc Sơn",
      "Huyện Bình Gia",
      "Huyện Cao Lộc",
      "Huyện Chi Lăng",
      "Huyện Đình Lập",
      "Huyện Hữu Lũng",
      "Huyện Lộc Bình",
      "Huyện Tràng Định",
      "Huyện Văn Lãng",
      "Huyện Văn Quan"
    ],
    "Lào Cai": [
      "TP. Lào Cai",
      "Thị xã Sa Pa",
      "Huyện Bắc Hà",
      "Huyện Bảo Thắng",
      "Huyện Bảo Yên",
      "Huyện Bát Xát",
      "Huyện Mường Khương",
      "Huyện Si Ma Cai",
      "Huyện Văn Bàn"
    ],
    "Long An": [
      "TP. Tân An",
      "Thị xã Kiến Tường",
      "Huyện Bến Lức",
      "Huyện Cần Đước",
      "Huyện Cần Giuộc",
      "Huyện Châu Thành",
      "Huyện Đức Hòa",
      "Huyện Đức Huệ",
      "Huyện Mộc Hóa",
      "Huyện Tân Hưng",
      "Huyện Tân Thạnh",
      "Huyện Tân Trụ",
      "Huyện Thạnh Hóa",
      "Huyện Thủ Thừa",
      "Huyện Vĩnh Hưng"
    ],
    "Nam Định": [
      "TP. Nam Định",
      "Huyện Giao Thủy",
      "Huyện Hải Hậu",
      "Huyện Mỹ Lộc",
      "Huyện Nam Trực",
      "Huyện Nghĩa Hưng",
      "Huyện Trực Ninh",
      "Huyện Vụ Bản",
      "Huyện Xuân Trường",
      "Huyện Ý Yên"
    ],
    "Nghệ An": [
      "TP. Vinh",
      "Thị xã Cửa Lò",
      "Thị xã Hoàng Mai",
      "Thị xã Thái Hòa",
      "Huyện Anh Sơn",
      "Huyện Con Cuông",
      "Huyện Diễn Châu",
      "Huyện Đô Lương",
      "Huyện Hưng Nguyên",
      "Huyện Kỳ Sơn",
      "Huyện Nam Đàn",
      "Huyện Nghi Lộc",
      "Huyện Nghĩa Đàn",
      "Huyện Quế Phong",
      "Huyện Quỳ Châu",
      "Huyện Quỳ Hợp",
      "Huyện Quỳnh Lưu",
      "Huyện Tân Kỳ",
      "Huyện Thanh Chương",
      "Huyện Tương Dương",
      "Huyện Yên Thành"
    ],
    "Ninh Bình": [
      "TP. Ninh Bình",
      "TP. Tam Điệp",
      "Huyện Gia Viễn",
      "Huyện Hoa Lư",
      "Huyện Kim Sơn",
      "Huyện Nho Quan",
      "Huyện Yên Khánh",
      "Huyện Yên Mô"
    ],
    "Ninh Thuận": [
      "TP. Phan Rang-Tháp Chàm",
      "Huyện Bác Ái",
      "Huyện Ninh Hải",
      "Huyện Ninh Phước",
      "Huyện Ninh Sơn",
      "Huyện Thuận Bắc",
      "Huyện Thuận Nam"
    ],
    "Phú Thọ": [
      "TP. Việt Trì",
      "Thị xã Phú Thọ",
      "Huyện Cẩm Khê",
      "Huyện Đoan Hùng",
      "Huyện Hạ Hòa",
      "Huyện Lâm Thao",
      "Huyện Phù Ninh",
      "Huyện Tam Nông",
      "Huyện Tân Sơn",
      "Huyện Thanh Ba",
      "Huyện Thanh Sơn",
      "Huyện Thanh Thủy",
      "Huyện Yên Lập"
    ],
    "Phú Yên": [
      "TP. Tuy Hòa",
      "Thị xã Sông Cầu",
      "Huyện Đông Hòa",
      "Huyện Đồng Xuân",
      "Huyện Phú Hòa",
      "Huyện Sơn Hòa",
      "Huyện Sông Hinh",
      "Huyện Tây Hòa",
      "Huyện Tuy An"
    ],
    "Quảng Bình": [
      "TP. Đồng Hới",
      "Thị xã Ba Đồn",
      "Huyện Bố Trạch",
      "Huyện Lệ Thủy",
      "Huyện Minh Hóa",
      "Huyện Quảng Ninh",
      "Huyện Quảng Trạch",
      "Huyện Tuyên Hóa"
    ],
    "Quảng Nam": [
      "TP. Tam Kỳ",
      "TP. Hội An",
      "Huyện Bắc Trà My",
      "Huyện Đại Lộc",
      "Huyện Điện Bàn",
      "Huyện Đông Giang",
      "Huyện Duy Xuyên",
      "Huyện Hiệp Đức",
      "Huyện Nam Giang",
      "Huyện Nam Trà My",
      "Huyện Nông Sơn",
      "Huyện Núi Thành",
      "Huyện Phú Ninh",
      "Huyện Phước Sơn",
      "Huyện Quế Sơn",
      "Huyện Tây Giang",
      "Huyện Thăng Bình",
      "Huyện Tiên Phước"
    ],
    "Quảng Ngãi": [
      "TP. Quảng Ngãi",
      "Huyện Ba Tơ",
      "Huyện Bình Sơn",
      "Huyện Đức Phổ",
      "Huyện Lý Sơn",
      "Huyện Minh Long",
      "Huyện Mộ Đức",
      "Huyện Nghĩa Hành",
      "Huyện Sơn Hà",
      "Huyện Sơn Tây",
      "Huyện Sơn Tịnh",
      "Huyện Tây Trà",
      "Huyện Trà Bồng",
      "Huyện Tư Nghĩa"
    ],
    "Quảng Ninh": [
      "TP. Hạ Long",
      "TP. Cẩm Phả",
      "TP. Móng Cái",
      "TP. Uông Bí",
      "Thị xã Đông Triều",
      "Thị xã Quảng Yên",
      "Huyện Ba Chẽ",
      "Huyện Bình Liêu",
      "Huyện Cô Tô",
      "Huyện Đầm Hà",
      "Huyện Hải Hà",
      "Huyện Tiên Yên",
      "Huyện Vân Đồn"
    ],
    "Quảng Trị": [
      "TP. Đông Hà",
      "Thị xã Quảng Trị",
      "Huyện Cam Lộ",
      "Huyện Cồn Cỏ",
      "Huyện Đa Krông",
      "Huyện Gio Linh",
      "Huyện Hải Lăng",
      "Huyện Hướng Hóa",
      "Huyện Triệu Phong",
      "Huyện Vĩnh Linh"
    ],
    "Sóc Trăng": [
      "TP. Sóc Trăng",
      "Thị xã Ngã Năm",
      "Thị xã Vĩnh Châu",
      "Huyện Châu Thành",
      "Huyện Cù Lao Dung",
      "Huyện Kế Sách",
      "Huyện Long Phú",
      "Huyện Mỹ Tú",
      "Huyện Mỹ Xuyên",
      "Huyện Thạnh Trị",
      "Huyện Trần Đề"
    ],
    "Sơn La": [
      "TP. Sơn La",
      "Huyện Bắc Yên",
      "Huyện Mai Sơn",
      "Huyện Mộc Châu",
      "Huyện Mường La",
      "Huyện Phù Yên",
      "Huyện Quỳnh Nhai",
      "Huyện Sông Mã",
      "Huyện Sốp Cộp",
      "Huyện Thuận Châu",
      "Huyện Vân Hồ",
      "Huyện Yên Châu"
    ],
    "Tây Ninh": [
      "TP. Tây Ninh",
      "Huyện Bến Cầu",
      "Huyện Châu Thành",
      "Huyện Dương Minh Châu",
      "Huyện Gò Dầu",
      "Huyện Hòa Thành",
      "Huyện Tân Biên",
      "Huyện Tân Châu",
      "Huyện Trảng Bàng"
    ],
    "Thái Bình": [
      "TP. Thái Bình",
      "Huyện Đông Hưng",
      "Huyện Hưng Hà",
      "Huyện Kiến Xương",
      "Huyện Quỳnh Phụ",
      "Huyện Thái Thụy",
      "Huyện Tiền Hải",
      "Huyện Vũ Thư"
    ],
    "Thái Nguyên": [
      "TP. Thái Nguyên",
      "TP. Sông Công",
      "TP. Phổ Yên",
      "Huyện Đại Từ",
      "Huyện Định Hóa",
      "Huyện Đồng Hỷ",
      "Huyện Phú Bình",
      "Huyện Phú Lương",
      "Huyện Võ Nhai"
    ],
    "Thanh Hóa": [
      "TP. Thanh Hóa",
      "TP. Sầm Sơn",
      "Thị xã Bỉm Sơn",
      "Thị xã Nghi Sơn",
      "Huyện Bá Thước",
      "Huyện Cẩm Thủy",
      "Huyện Đông Sơn",
      "Huyện Hà Trung",
      "Huyện Hậu Lộc",
      "Huyện Hoằng Hóa",
      "Huyện Lang Chánh",
      "Huyện Mường Lát",
      "Huyện Nga Sơn",
      "Huyện Ngọc Lặc",
      "Huyện Như Thanh",
      "Huyện Như Xuân",
      "Huyện Nông Cống",
      "Huyện Quan Hóa",
      "Huyện Quan Sơn",
      "Huyện Quảng Xương",
      "Huyện Thạch Thành",
      "Huyện Thiệu Hóa",
      "Huyện Thọ Xuân",
      "Huyện Thường Xuân",
      "Huyện Triệu Sơn",
      "Huyện Vĩnh Lộc",
      "Huyện Yên Định"
    ],
    "Thừa Thiên Huế": [
      "TP. Huế",
      "Thị xã Hương Thủy",
      "Thị xã Hương Trà",
      "Huyện A Lưới",
      "Huyện Nam Đông",
      "Huyện Phong Điền",
      "Huyện Phú Lộc",
      "Huyện Phú Vang",
      "Huyện Quảng Điền"
    ],
    "Tiền Giang": [
      "TP. Mỹ Tho",
      "Thị xã Cai Lậy",
      "Thị xã Gò Công",
      "Huyện Cái Bè",
      "Huyện Cai Lậy",
      "Huyện Châu Thành",
      "Huyện Chợ Gạo",
      "Huyện Gò Công Đông",
      "Huyện Gò Công Tây",
      "Huyện Tân Phú Đông",
      "Huyện Tân Phước"
    ],
    "TP Hồ Chí Minh": [
      "Quận 1",
      "Quận 3",
      "Quận 4",
      "Quận 5",
      "Quận 6",
      "Quận 7",
      "Quận 8",
      "Quận 10",
      "Quận 11",
      "Quận 12",
      "Quận Bình Tân",
      "Quận Bình Thạnh",
      "Quận Gò Vấp",
      "Quận Phú Nhuận",
      "Quận Tân Bình",
      "Quận Tân Phú",
      "TP Thủ Đức",
      "Huyện Bình Chánh",
      "Huyện Cần Giờ",
      "Huyện Củ Chi",
      "Huyện Hóc Môn",
      "Huyện Nhà Bè"
    ],
    "Trà Vinh": [
      "TP. Trà Vinh",
      "Thị xã Duyên Hải",
      "Huyện Càng Long",
      "Huyện Cầu Kè",
      "Huyện Cầu Ngang",
      "Huyện Châu Thành",
      "Huyện Duyên Hải",
      "Huyện Tiểu Cần",
      "Huyện Trà Cú"
    ],
    "Tuyên Quang": [
      "TP. Tuyên Quang",
      "Huyện Chiêm Hóa",
      "Huyện Hàm Yên",
      "Huyện Lâm Bình",
      "Huyện Na Hang",
      "Huyện Sơn Dương",
      "Huyện Yên Sơn"
    ],
    "Vĩnh Long": [
      "TP. Vĩnh Long",
      "Thị xã Bình Minh",
      "Huyện Bình Tân",
      "Huyện Long Hồ",
      "Huyện Mang Thít",
      "Huyện Tam Bình",
      "Huyện Trà Ôn",
      "Huyện Vũng Liêm"
    ],
    "Vĩnh Phúc": [
      "TP. Vĩnh Yên",
      "TP. Phúc Yên",
      "Huyện Bình Xuyên",
      "Huyện Lập Thạch",
      "Huyện Sông Lô",
      "Huyện Tam Đảo",
      "Huyện Tam Dương",
      "Huyện Vĩnh Tường",
      "Huyện Yên Lạc"
    ],
    "Yên Bái": [
      "TP. Yên Bái",
      "TP. Nghĩa Lộ",
      "Huyện Lục Yên",
      "Huyện Mù Căng Chải",
      "Huyện Trạm Tấu",
      "Huyện Trấn Yên",
      "Huyện Văn Chấn",
      "Huyện Văn Yên",
      "Huyện Yên Bình"
    ]
  },

  // Extended wards data - added more districts compared to original
  wards: {
    "Quận 1": [
      "Phường Bến Nghé",
      "Phường Bến Thành",
      "Phường Cầu Kho",
      "Phường Cầu Ông Lãnh",
      "Phường Cô Giang",
      "Phường Đa Kao",
      "Phường Nguyễn Cư Trinh",
      "Phường Nguyễn Thái Bình",
      "Phường Phạm Ngũ Lão",
      "Phường Tân Định"
    ],
    "Quận 3": [
      "Phường 1",
      "Phường 2",
      "Phường 3",
      "Phường 4",
      "Phường 5",
      "Phường 6",
      "Phường 7",
      "Phường 8",
      "Phường 9",
      "Phường 10",
      "Phường 11",
      "Phường 12",
      "Phường 13",
      "Phường 14"
    ],
    "Quận 4": [
      "Phường 1",
      "Phường 2",
      "Phường 3",
      "Phường 4",
      "Phường 5",
      "Phường 6",
      "Phường 8",
      "Phường 9",
      "Phường 10",
      "Phường 13",
      "Phường 14",
      "Phường 15",
      "Phường 16",
      "Phường 18"
    ],
    "Quận 5": [
      "Phường 1",
      "Phường 2",
      "Phường 3",
      "Phường 4",
      "Phường 5",
      "Phường 6",
      "Phường 7",
      "Phường 8",
      "Phường 9",
      "Phường 10",
      "Phường 11",
      "Phường 12",
      "Phường 13",
      "Phường 14",
      "Phường 15"
    ],
    "Quận Hoàn Kiếm": [
      "Phường Chương Dương",
      "Phường Cửa Đông",
      "Phường Cửa Nam",
      "Phường Đồng Xuân",
      "Phường Hàng Bạc",
      "Phường Hàng Bài",
      "Phường Hàng Bồ",
      "Phường Hàng Bông",
      "Phường Hàng Buồm",
      "Phường Hàng Đào",
      "Phường Hàng Gai",
      "Phường Hàng Mã",
      "Phường Hàng Trống",
      "Phường Lý Thái Tổ",
      "Phường Phan Chu Trinh",
      "Phường Phúc Tân",
      "Phường Trần Hưng Đạo",
      "Phường Tràng Tiền"
    ],
    "Quận Hai Bà Trưng": [
      "Phường Bạch Đằng",
      "Phường Bách Khoa",
      "Phường Bạch Mai",
      "Phường Cầu Dền",
      "Phường Đống Mác",
      "Phường Đồng Nhân",
      "Phường Đồng Tâm",
      "Phường Lê Đại Hành",
      "Phường Minh Khai",
      "Phường Ngô Thì Nhậm",
      "Phường Nguyễn Du",
      "Phường Phạm Đình Hổ",
      "Phường Phố Huế",
      "Phường Quỳnh Lôi",
      "Phường Quỳnh Mai",
      "Phường Thanh Lương",
      "Phường Thanh Nhàn",
      "Phường Trương Định",
      "Phường Vĩnh Tuy"
    ],
    "Quận Đống Đa": [
      "Phường Cát Linh",
      "Phường Hàng Bột",
      "Phường Khâm Thiên",
      "Phường Khương Thượng",
      "Phường Kim Liên",
      "Phường Láng Hạ",
      "Phường Láng Thượng",
      "Phường Nam Đồng",
      "Phường Ngã Tư Sở",
      "Phường Ô Chợ Dừa",
      "Phường Phương Liên",
      "Phường Phương Mai",
      "Phường Quang Trung",
      "Phường Quốc Tử Giám",
      "Phường Thịnh Quang",
      "Phường Trung Liệt",
      "Phường Trung Phụng",
      "Phường Trung Tự",
      "Phường Văn Chương",
      "Phường Văn Miếu"
    ],
    "Quận Cầu Giấy": [
      "Phường Dịch Vọng",
      "Phường Dịch Vọng Hậu",
      "Phường Mai Dịch",
      "Phường Nghĩa Đô",
      "Phường Nghĩa Tân",
      "Phường Quan Hoa",
      "Phường Trung Hòa",
      "Phường Yên Hòa"
    ],
    "Quận Thanh Xuân": [
      "Phường Hạ Đình",
      "Phường Khương Đình",
      "Phường Khương Mai",
      "Phường Khương Trung",
      "Phường Kim Giang",
      "Phường Nhân Chính",
      "Phường Phương Liệt",
      "Phường Thanh Xuân Bắc",
      "Phường Thanh Xuân Nam",
      "Phường Thanh Xuân Trung",
      "Phường Thượng Đình"
    ],
    "Quận Tây Hồ": [
      "Phường Bưởi",
      "Phường Nhật Tân",
      "Phường Phú Thượng",
      "Phường Quảng An",
      "Phường Thụy Khuê",
      "Phường Tứ Liên",
      "Phường Xuân La",
      "Phường Yên Phụ"
    ],
    "Quận Long Biên": [
      "Phường Bồ Đề",
      "Phường Cự Khối",
      "Phường Đức Giang",
      "Phường Gia Thụy",
      "Phường Giang Biên",
      "Phường Long Biên",
      "Phường Ngọc Lâm",
      "Phường Ngọc Thụy",
      "Phường Phúc Đồng",
      "Phường Phúc Lợi",
      "Phường Sài Đồng",
      "Phường Thạch Bàn",
      "Phường Thượng Thanh",
      "Phường Việt Hưng"
    ],
    "Quận Hà Đông": [
      "Phường Biên Giang",
      "Phường Đồng Mai",
      "Phường Hà Cầu",
      "Phường Kiến Hưng",
      "Phường La Khê",
      "Phường Mộ Lao",
      "Phường Nguyễn Trãi",
      "Phường Phú La",
      "Phường Phú Lãm",
      "Phường Phú Lương",
      "Phường Phúc La",
      "Phường Quang Trung",
      "Phường Vạn Phúc",
      "Phường Văn Quán",
      "Phường Yên Nghĩa",
      "Phường Yết Kiêu"
    ],
    "Quận Nam Từ Liêm": [
      "Phường Cầu Diễn",
      "Phường Đại Mỗ",
      "Phường Mễ Trì",
      "Phường Mỹ Đình 1",
      "Phường Mỹ Đình 2",
      "Phường Phú Đô",
      "Phường Phương Canh",
      "Phường Tây Mỗ",
      "Phường Trung Văn",
      "Phường Xuân Phương"
    ],
    "Quận Bắc Từ Liêm": [
      "Phường Cổ Nhuế 1",
      "Phường Cổ Nhuế 2",
      "Phường Đông Ngạc",
      "Phường Đức Thắng",
      "Phường Liên Mạc",
      "Phường Minh Khai",
      "Phường Phú Diễn",
      "Phường Phúc Diễn",
      "Phường Tây Tựu",
      "Phường Thượng Cát",
      "Phường Thụy Phương",
      "Phường Xuân Đỉnh",
      "Phường Xuân Tảo"
    ],
    "Quận Hoàng Mai": [
      "Phường Đại Kim",
      "Phường Định Công",
      "Phường Giáp Bát",
      "Phường Hoàng Liệt",
      "Phường Hoàng Văn Thụ",
      "Phường Lĩnh Nam",
      "Phường Mai Động",
      "Phường Tân Mai",
      "Phường Thanh Trì",
      "Phường Thịnh Liệt",
      "Phường Trần Phú",
      "Phường Tương Mai",
      "Phường Vĩnh Hưng",
      "Phường Yên Sở"
    ],
    "Quận Hải Châu": [
      "Phường Bình Hiên",
      "Phường Bình Thuận",
      "Phường Hải Châu I",
      "Phường Hải Châu II",
      "Phường Hòa Cường Bắc",
      "Phường Hòa Cường Nam",
      "Phường Hòa Thuận Đông",
      "Phường Hòa Thuận Tây",
      "Phường Nam Dương",
      "Phường Phước Ninh",
      "Phường Thạch Thang",
      "Phường Thanh Bình",
      "Phường Thuận Phước"
    ],
    "Quận Thanh Khê": [
      "Phường An Khê",
      "Phường Chính Gián",
      "Phường Hòa Khê",
      "Phường Tam Thuận",
      "Phường Tân Chính",
      "Phường Thạc Gián",
      "Phường Thanh Khê Đông",
      "Phường Thanh Khê Tây",
      "Phường Vĩnh Trung",
      "Phường Xuân Hà"
    ],
    "Quận Sơn Trà": [
      "Phường An Hải Bắc",
      "Phường An Hải Đông",
      "Phường An Hải Tây",
      "Phường Mân Thái",
      "Phường Nại Hiên Đông",
      "Phường Phước Mỹ",
      "Phường Thọ Quang"
    ],
    "Quận Ngũ Hành Sơn": [
      "Phường Hòa Hải",
      "Phường Hòa Quý",
      "Phường Khuê Mỹ",
      "Phường Mỹ An"
    ],
    "Quận Liên Chiểu": [
      "Phường Hòa Hiệp Bắc",
      "Phường Hòa Hiệp Nam",
      "Phường Hòa Khánh Bắc",
      "Phường Hòa Khánh Nam",
      "Phường Hòa Minh"
    ],
    "Quận Cẩm Lệ": [
      "Phường Hòa An",
      "Phường Hòa Phát",
      "Phường Hòa Thọ Đông",
      "Phường Hòa Thọ Tây",
      "Phường Hòa Xuân",
      "Phường Khuê Trung"
    ],
    "TP. Buôn Ma Thuột": [
      "Phường Ea Tam",
      "Phường Khánh Xuân",
      "Phường Tân An",
      "Phường Tân Hòa",
      "Phường Tân Lập",
      "Phường Tân Lợi",
      "Phường Tân Thành",
      "Phường Tân Tiến",
      "Phường Thắng Lợi",
      "Phường Thành Công",
      "Phường Thành Nhất",
      "Phường Thống Nhất",
      "Phường Tự An",
      "Xã Cư Êbur",
      "Xã Ea Kao",
      "Xã Ea Tu",
      "Xã Hòa Khánh",
      "Xã Hòa Phú",
      "Xã Hòa Thắng",
      "Xã Hòa Thuận",
      "Xã Hòa Xuân"
    ],
    "TP. Rạch Giá": [
      "Phường An Bình",
      "Phường An Hòa",
      "Phường Rạch Sỏi",
      "Phường Vĩnh Bảo",
      "Phường Vĩnh Hiệp",
      "Phường Vĩnh Lạc",
      "Phường Vĩnh Lợi",
      "Phường Vĩnh Quang",
      "Phường Vĩnh Thanh",
      "Phường Vĩnh Thanh Vân",
      "Phường Vĩnh Thông",
      "Xã Phi Thông"
    ],
    "TP. Biên Hòa": [
      "Phường An Bình",
      "Phường Bình Đa",
      "Phường Bửu Hòa",
      "Phường Bửu Long",
      "Phường Hố Nai",
      "Phường Hòa Bình",
      "Phường Long Bình",
      "Phường Long Bình Tân",
      "Phường Quang Vinh",
      "Phường Quyết Thắng",
      "Phường Tam Hiệp",
      "Phường Tam Hòa",
      "Phường Tân Biên",
      "Phường Tân Hòa",
      "Phường Tân Hiệp",
      "Phường Tân Mai",
      "Phường Tân Phong",
      "Phường Tân Tiến",
      "Phường Tân Vạn",
      "Phường Thanh Bình",
      "Phường Thống Nhất",
      "Phường Trảng Dài",
      "Xã An Hòa",
      "Xã Hiệp Hòa",
      "Xã Hóa An",
      "Xã Long Hưng",
      "Xã Phước Tân",
      "Xã Tam Phước",
      "Xã Tân Hạnh",
      "Xã Tân Phước"
    ],
    "TP. Nha Trang": [
      "Phường Lộc Thọ",
      "Phường Ngọc Hiệp",
      "Phường Phước Hải",
      "Phường Phước Hòa",
      "Phường Phước Long",
      "Phường Phước Tân",
      "Phường Phước Tiến",
      "Phường Phương Sài",
      "Phường Phương Sơn",
      "Phường Tân Lập",
      "Phường Vạn Thắng",
      "Phường Vạn Thạnh",
      "Phường Vĩnh Hải",
      "Phường Vĩnh Hòa",
      "Phường Vĩnh Nguyên",
      "Phường Vĩnh Phước",
      "Phường Vĩnh Thọ",
      "Phường Vĩnh Trường",
      "Phường Xương Huân",
      "Xã Phước Đồng",
      "Xã Vĩnh Hiệp",
      "Xã Vĩnh Lương",
      "Xã Vĩnh Ngọc",
      "Xã Vĩnh Phương",
      "Xã Vĩnh Thái",
      "Xã Vĩnh Thạnh",
      "Xã Vĩnh Trung"
    ],
    "TP. Pleiku": [
      "Phường Chi Lăng",
      "Phường Diên Hồng",
      "Phường Đống Đa",
      "Phường Hội Phú",
      "Phường Hội Thương",
      "Phường Ia Kring",
      "Phường Phù Đổng",
      "Phường Tây Sơn",
      "Phường Thắng Lợi",
      "Phường Thống Nhất",
      "Phường Trà Bá",
      "Phường Yên Đỗ",
      "Phường Yên Thế",
      "Xã An Phú",
      "Xã Biển Hồ",
      "Xã Chư Á",
      "Xã Chư Hdrông",
      "Xã Diên Phú",
      "Xã Gào",
      "Xã Ia Kênh",
      "Xã Tân Sơn",
      "Xã Trà Đa"
    ],
    "TP Thủ Đức": [
      "Phường An Khánh",
      "Phường An Lợi Đông",
      "Phường An Phú",
      "Phường Bình Chiểu",
      "Phường Bình Thọ",
      "Phường Bình Trưng Đông",
      "Phường Bình Trưng Tây",
      "Phường Cát Lái",
      "Phường Hiệp Bình Chánh",
      "Phường Hiệp Bình Phước",
      "Phường Hiệp Phú",
      "Phường Linh Chiểu",
      "Phường Linh Đông",
      "Phường Linh Tây",
      "Phường Linh Trung",
      "Phường Linh Xuân",
      "Phường Long Bình",
      "Phường Long Phước",
      "Phường Long Thạnh Mỹ",
      "Phường Long Trường",
      "Phường Phú Hữu",
      "Phường Phước Bình",
      "Phường Phước Long A",
      "Phường Phước Long B",
      "Phường Tam Bình",
      "Phường Tam Phú",
      "Phường Tăng Nhơn Phú A",
      "Phường Tăng Nhơn Phú B",
      "Phường Tân Phú",
      "Phường Thảo Điền",
      "Phường Thủ Thiêm",
      "Phường Trường Thạnh",
      "Phường Trường Thọ"
    ],
    "TP. Huế": [
      "Phường An Cựu",
      "Phường An Đông",
      "Phường An Hòa",
      "Phường An Tây",
      "Phường Đông Ba",
      "Phường Gia Hội",
      "Phường Hương Long",
      "Phường Hương Sơ",
      "Phường Kim Long",
      "Phường Phú Bình",
      "Phường Phú Cát",
      "Phường Phú Hậu",
      "Phường Phú Hiệp",
      "Phường Phú Hòa",
      "Phường Phú Hội",
      "Phường Phú Nhuận",
      "Phường Phú Thuận",
      "Phường Phước Vĩnh",
      "Phường Phường Đúc",
      "Phường Tây Lộc",
      "Phường Thuận Hòa",
      "Phường Thuận Lộc",
      "Phường Thuận Thành",
      "Phường Trường An",
      "Phường Vĩnh Ninh",
      "Phường Xuân Phú",
      "Xã Hải Dương",
      "Xã Hương Phong",
      "Xã Thủy Bằng",
      "Xã Thủy Vân",
      "Xã Thủy Xuân"
    ],
    "TP. Vinh": [
      "Phường Bến Thủy",
      "Phường Cửa Nam",
      "Phường Đội Cung",
      "Phường Đông Vĩnh",
      "Phường Hà Huy Tập",
      "Phường Hồng Sơn",
      "Phường Hưng Bình",
      "Phường Hưng Dũng",
      "Phường Hưng Phúc",
      "Phường Lê Lợi",
      "Phường Lê Mao",
      "Phường Quán Bàu",
      "Phường Quang Trung",
      "Phường Trung Đô",
      "Phường Trường Thi",
      "Phường Vinh Tân",
      "Xã Hưng Chính",
      "Xã Hưng Đông",
      "Xã Hưng Hòa",
      "Xã Hưng Lộc",
      "Xã Nghi Ân",
      "Xã Nghi Đức",
      "Xã Nghi Kim",
      "Xã Nghi Liên"
    ],
    "TP. Đà Lạt": [
      "Phường 1",
      "Phường 2",
      "Phường 3",
      "Phường 4",
      "Phường 5",
      "Phường 6",
      "Phường 7",
      "Phường 8",
      "Phường 9",
      "Phường 10",
      "Phường 11",
      "Phường 12",
      "Xã Tà Nung",
      "Xã Trạm Hành",
      "Xã Xuân Thọ",
      "Xã Xuân Trường"
    ],
    "TP. Cần Thơ": [
      "Phường An Hòa",
      "Phường An Khánh",
      "Phường An Nghiệp",
      "Phường An Phú",
      "Phường Cái Khế",
      "Phường Hưng Lợi",
      "Phường Hưng Phú",
      "Phường Hưng Thạnh",
      "Phường Tân An",
      "Phường Thới Bình",
      "Phường Xuân Khánh",
      "Xã Thới An Đông"
    ],
    "Quận Bình Tân": [
      "Phường An Lạc",
      "Phường An Lạc A",
      "Phường Bình Hưng Hòa",
      "Phường Bình Hưng Hòa A",
      "Phường Bình Hưng Hòa B",
      "Phường Bình Trị Đông",
      "Phường Bình Trị Đông A",
      "Phường Bình Trị Đông B",
      "Phường Tân Tạo",
      "Phường Tân Tạo A"
    ],
    "Quận Bình Thạnh": [
      "Phường 1",
      "Phường 2",
      "Phường 3",
      "Phường 5",
      "Phường 6",
      "Phường 7",
      "Phường 11",
      "Phường 12",
      "Phường 13",
      "Phường 14",
      "Phường 15",
      "Phường 17",
      "Phường 19",
      "Phường 21",
      "Phường 22",
      "Phường 24",
      "Phường 25",
      "Phường 26",
      "Phường 27",
      "Phường 28"
    ],
    "Quận Gò Vấp": [
      "Phường 1",
      "Phường 3",
      "Phường 4",
      "Phường 5",
      "Phường 6",
      "Phường 7",
      "Phường 8",
      "Phường 9",
      "Phường 10",
      "Phường 11",
      "Phường 12",
      "Phường 13",
      "Phường 14",
      "Phường 15",
      "Phường 16",
      "Phường 17"
    ],
    "Quận Phú Nhuận": [
      "Phường 1",
      "Phường 2",
      "Phường 3",
      "Phường 4",
      "Phường 5",
      "Phường 7",
      "Phường 8",
      "Phường 9",
      "Phường 10",
      "Phường 11",
      "Phường 13",
      "Phường 14",
      "Phường 15",
      "Phường 17"
    ],
    "Quận Tân Bình": [
      "Phường 1",
      "Phường 2",
      "Phường 3",
      "Phường 4",
      "Phường 5",
      "Phường 6",
      "Phường 7",
      "Phường 8",
      "Phường 9",
      "Phường 10",
      "Phường 11",
      "Phường 12",
      "Phường 13",
      "Phường 14",
      "Phường 15"
    ],
    "Quận Tân Phú": [
      "Phường Hiệp Tân",
      "Phường Hòa Thạnh",
      "Phường Phú Thạnh",
      "Phường Phú Thọ Hòa",
      "Phường Phú Trung",
      "Phường Sơn Kỳ",
      "Phường Tân Quý",
      "Phường Tân Sơn Nhì",
      "Phường Tân Thành",
      "Phường Tân Thới Hòa",
      "Phường Tây Thạnh"
    ],
    "Huyện Củ Chi": [
      "Thị trấn Củ Chi",
      "Xã An Nhơn Tây",
      "Xã An Phú",
      "Xã Bình Mỹ",
      "Xã Hòa Phú",
      "Xã Nhuận Đức",
      "Xã Phạm Văn Cội",
      "Xã Phú Hòa Đông",
      "Xã Phú Mỹ Hưng",
      "Xã Phước Hiệp",
      "Xã Phước Thạnh",
      "Xã Phước Vĩnh An",
      "Xã Tân An Hội",
      "Xã Tân Phú Trung",
      "Xã Tân Thạnh Đông",
      "Xã Tân Thạnh Tây",
      "Xã Tân Thông Hội",
      "Xã Thái Mỹ",
      "Xã Trung An",
      "Xã Trung Lập Hạ",
      "Xã Trung Lập Thượng"
    ],
    "Huyện Hóc Môn": [
      "Thị trấn Hóc Môn",
      "Xã Bà Điểm",
      "Xã Đông Thạnh",
      "Xã Nhị Bình",
      "Xã Tân Hiệp",
      "Xã Tân Thới Nhì",
      "Xã Tân Xuân",
      "Xã Thới Tam Thôn",
      "Xã Trung Chánh",
      "Xã Xuân Thới Đông",
      "Xã Xuân Thới Sơn",
      "Xã Xuân Thới Thượng"
    ],
    "Huyện Nhà Bè": [
      "Thị trấn Nhà Bè",
      "Xã Hiệp Phước",
      "Xã Long Thới",
      "Xã Nhơn Đức",
      "Xã Phú Xuân",
      "Xã Phước Kiển",
      "Xã Phước Lộc"
    ],
    "Huyện Bình Chánh": [
      "Thị trấn Tân Túc",
      "Xã An Phú Tây",
      "Xã Bình Chánh",
      "Xã Bình Hưng",
      "Xã Bình Lợi",
      "Xã Đa Phước",
      "Xã Hưng Long",
      "Xã Lê Minh Xuân",
      "Xã Phạm Văn Hai",
      "Xã Phong Phú",
      "Xã Quy Đức",
      "Xã Tân Kiên",
      "Xã Tân Nhựt",
      "Xã Tân Quý Tây",
      "Xã Vĩnh Lộc A",
      "Xã Vĩnh Lộc B"
    ],
    "Huyện Cần Giờ": [
      "Thị trấn Cần Thạnh",
      "Xã An Thới Đông",
      "Xã Bình Khánh",
      "Xã Long Hòa",
      "Xã Lý Nhơn",
      "Xã Tam Thôn Hiệp",
      "Xã Thạnh An"
    ]
  }
};

export default locationData;